nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiusculas é: {}.'.format(nome.upper()))
print('Seu nome em minusculas é: {}.'.format(nome.lower()))
print('Seu nome ao todo tem {} letras.'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras.'.format(nome.find(' ')))
separa = nome.split()
print(separa)
print('Seu primeiro nome tem {} letras.'.format(len(separa[0])))
print('Seu primeiro nome é {}.'.format(separa[0]))

